### PR TITLE
Create PSF subpackage

### PR DESCRIPTION
**Pull request by mirca**
This PR creates a module to accommodate the necessary tools for doing point spread function photometry.
Does that suffice?
cc @hamogu @bsipocz @eteq

### CODE REVIEW

**Comment by mirca** [comment]
Any clue why the coverage dropped?

**Comment by larrybradley** [comment]
@mirca You need to add an empty `psf/tests/__init__.py` file to run the PSF tests.  Just copy this file:
https://github.com/astropy/photutils/blob/master/photutils/tests/__init__.py

I also changed this PR title since you are converting an existing module (psf.py) to a subpackage.

**Comment by larrybradley** [comment]
@mirca The PSF tests are running now, but you also need to update the imports in the PSF test modules:  `from ..psf import` to `from ..core import`

Also, I would recommend changing the filename of `test_psfs.py` to `test_core.py`.  It's nice to have a test module with the same name as the module (i.e. `test_<module>.py`).

**Comment by mirca** [comment]
@larrybradley Thanks!

**Comment by larrybradley** [comment]
Thanks, @mirca.  Is this PR done or should I wait to merge?

**Comment by mirca** [comment]
@hamogu, @bsipocz or @eteq Sounds good?

**Comment by larrybradley** [comment]
This looks good and is needed for upcoming PSF changes, so I'm going to merge this now.

**Pull request merged**
