### PR TITLE
Add an 'isophote' subpackage

### PR DESCRIPTION
**Pull request by larrybradley**
I had some trouble adding commits to #532, so I started a new PR.

I made a number of changes to #532 in order to get the tests (and doctests) to pass and the docs to build without warnings.  I also made several improvement to speed up the code and tests, replacing loops where easily possible, and some API changes (names of classes for consistency).  With my changes the tests now run about 50% faster.

There are still several places where this code uses looping.  With some effort, I think those loops can be replaced to further speed up the code. 

I will add the notebooks to the `photutils-datasets` repo.

### CODE REVIEW

**Comment by larrybradley** [comment]
Many thanks, @ibusko!  Merging now.

CC: @SaraOgaz, @pllim

**Comment by pllim** [comment]
@larrybradley , when is this going to be in a release? 🎉

**Comment by larrybradley** [comment]
@pllim Soon!  The spooktacular `0.4` release is targeted by Oct. 31.

**Comment by pllim** [comment]
@larrybradley hopefully will be :spider: free... :bat:

**Pull request merged**
