### PR TITLE
Add a generic model-based image generator [fixed]

### PR DESCRIPTION
**Pull request by larrybradley**
This fixes PR https://github.com/astropy/photutils/pull/474  (I don't have permission to update #474 directly).

The other changes discussed in #474 will come in a separate PR.

### CODE REVIEW

**Comment by larrybradley** [comment]
@bsipocz I think @eteq must not have checked the "allow edits" box or his repo is protected somehow.

**Comment by bsipocz** [comment]
Oh. I always assumed that the ``Add more commits by pushing to the eteq-re-make-make branch on larrybradley/photutils.`` line is only present when the box is checked.

**Comment by larrybradley** [comment]
@bsipocz That's a branch in my repo (which does allow edits).

**Comment by bsipocz** [comment]
Sure, I meant that #474 have a similar line, but was easier to copy the one from here. Anyway I was just curious why it didn't work.

**Comment by larrybradley** [comment]
@bsipocz Sorry, I did catch that (see my edit) above).  Just wondering why it didn't work.  Can you add edits to #474?

**Comment by bsipocz** [comment]
@larrybradley - It worked. I think I know the reason it doesn't work for you. Which protocol do you try to push it with? I add the remotes with the same ones I have my fork (git@), and now I vaguely recall the reason was that I had problems when tried to push with the default (https? git://?).

**Comment by larrybradley** [comment]
@bsipocz Many thanks!  That solved it!  I was pushing to the remote using the http protocol instead of ssh.  Closing this PR (see #474).

**Pull request closed without merging**
