### PR TITLE
Updating versions for CIs

### PR DESCRIPTION
**Pull request by bsipocz**
Update numpy and astropy versions for both travis and appveyor, and adding a build against the numpy prerelease for travis (as well as the now old 1.10).

### CODE REVIEW

**Comment by bsipocz** [comment]
Oops, I think we had the same thing in mind with @larrybradley.

**Comment by larrybradley** [comment]
I must have push just a minute before you! 😄

**Comment by larrybradley** [comment]
Let's merge this one first and then I can rebase mine.  I think I have a few more `travis-ci` changes.

**Comment by larrybradley** [comment]
@bsipocz Do you know what's going on with the `travis-ci` `numpy` dev test?

In this PR, the `setup.py` fails (https://travis-ci.org/astropy/photutils/jobs/134514469).

In my PR, the `setup.py` works (even though that test is identical to yours), but `travis-ci` fails without actually reporting the failure.  The tests just seem to stop (https://travis-ci.org/astropy/photutils/jobs/134514155).

In any case, I was also thinking that perhaps we should make the `numpy` dev version test as an "Allowed Failure", like it is in `Astropy`.  What do you think?

**Comment by bsipocz** [comment]
@larrybradley - I have no idea what's wrong with this numpy prerelease, looks like the builds are halting and the ultimately time out. I saw this with other packages, too.

 Without a traceback it's difficult to do anything, so :+1:  to put it into allowed failures.

(The build there failed as ``SETUP_CMD`` wasn't defined as a global variable.

**Comment by larrybradley** [comment]
Thanks, @bsipocz.

**Pull request merged**
