### PR TITLE
Add verbose mode to ellipse fitting and modeling

### PR DESCRIPTION
**Pull request by ibusko**
This addresses #891 and #823

### CODE REVIEW

**Comment by bsipocz** [comment]
What about having logger verbosity rather than explicit prints? That would fit much nicer into a pipeline environment.

**Comment by ibusko** [comment]
@bsipocz that would be nice too, but I wonder how that would work in a, say, notebook environment. I never though of this package as something that can be used in a pipeline environment, due to the highly interactive nature of the data analysis that it performs. But if we can have the logger perform by default as the plain stdout prints we have now, it would be easy to convert the print code to logger calls.

**Comment by larrybradley** [comment]
@ibusko Astropy's logger works fine in a notebook environment.  The advantage of the logger, of course, is it can be turned off by the user.

```python
from astropy import log
log.info('my message')
```

**Comment by ibusko** [comment]
@larrybradley that's good. Still, I wonder if the logger can be used to create a stdout-based progress-bar-like output like I have in this PR. The point is not really to log anything for posterior use, but to give the user a real-time visual feedback on the fit's progress, while it's happening. The stdout output is not meant to be kept, or used for anything else, much less for science. It may lack the numerical precision available in the output table, as well as have incomplete information. The logger solution seemed to me to be an overkill for just visual feedback purposes. Of course, we can always have both, although I didn't find so far a use case where logging would be necessary. As @bsipocz pointed out, it would make all the sense in a pipeline or background multi-job environment, but I would advise against running the ellipse fitting algorithm in such way, since it typically needs significant "nursing" from the user.

**Comment by larrybradley** [comment]
@ibusko I manually merged this PR (2155dbdbd4ec61d49ccff83d4e3f9ba61ca9a55a) because your branch disappeared and had conflicts.

**Pull request closed without merging**
