### PR TITLE
Add tools to build (and fit) an effective PSF

### PR DESCRIPTION
**Pull request by larrybradley**
This large PR adds tools to build (and fit) an effective PSF (ePSF) following the prescription of Anderson & King (2000; PASP, 112 1360).

It also adds a new function to load a simulated HST WFC3/IR F160W image of stars (``load_simulated_hst_star_image``), which is used in the documentation.

### CODE REVIEW

**Comment by saimn** [comment]
I wanted to have a look at this interesting new module and at its documentation, but it looks like the docs building is often failing because of memory issues: https://readthedocs.org/projects/photutils/builds/ :disappointed:

**Comment by larrybradley** [comment]
RTD is actually failing because of timeouts (> 900 s to build).  I don't know why is says "memory issues".  For some reason it takes >~ 600 s just to create the environment (before the tests are even run).

**Comment by mirca** [comment]
This is awesome, @larrybradley! Thank you!

**Comment by larrybradley** [comment]
Thanks, @mirca!

**Pull request merged**
