### PR TITLE
Update numpy RandomState intersphinx link

### PR DESCRIPTION
**Pull request by larrybradley**
The numpy `RandomState` documentation is at `numpy.random.mtrand.RandomState`.

### CODE REVIEW

**Comment by bsipocz** [comment]
oh, this is weird, why did they change their namespace? Was it something consciously done, or rather an accident? Maybe @mhvk have an insight.

**Comment by larrybradley** [comment]
I'm only starting to look into this, but apparently in numpy 1.7 `RandomState` is considered a "legacy" generator.  The `numpy.random.mtrand.RandomState` intersphinx works with older `numpy`, but `numpy.random.RandomState` was removed.

In the bigger picture, I probably need to look into replacing `RandomState`.

**Comment by larrybradley** [comment]
https://docs.scipy.org/doc/numpy/reference/random/legacy.html

**Comment by larrybradley** [comment]
@bsipocz Unrelated -- `AppVeyor` is failing because the conda environment can't be built.  Is this a known 'ci-helpers` issue?

**Comment by bsipocz** [comment]
It's likely. I saw @pllim pinging about it in astropy core, can't promise an ETA to fix it, maybe have some time in the evening for it, but not during the day.

**Comment by larrybradley** [comment]
Merging this since the `AppVeyor` failure is unrelated.

**Comment by mhvk** [comment]
Indeed, `np.random` saw a huge rewrite. I've not followed it closely but people seemed to think it a big improvement.

**Pull request merged**
