### PR TITLE
Add a new case to circle-triangle intersection area

### LINKED ISSUE #242: Some tests in photutils/tests/test_aperture_photometry.py fail in linux i386
Hi, some tests in photutils/tests/test_aperture_photometry.py fail in linux i386, but no in x86_64
More details here:

https://kojipkgs.fedoraproject.org//work/tasks/9826/8719826/build.log

The tests are:
______________ TestElliptical.test_scalar_error_no_effective_gain ______________
____________ TestElliptical.test_scalar_error_scalar_effective_gain ____________
____________ TestElliptical.test_scalar_error_array_effective_gain _____________
______________ TestElliptical.test_array_error_no_effective_gain _______________
_____________ TestElliptical.test_array_error_array_effective_gain _____________
__________ TestEllipticalAnnulus.test_scalar_error_no_effective_gain ___________
________ TestEllipticalAnnulus.test_scalar_error_scalar_effective_gain _________
____ TestEllipticalAnnulus.test_quantity_scalar_error_scalar_effective_gain ____
_________ TestEllipticalAnnulus.test_scalar_error_array_effective_gain _________
___________ TestEllipticalAnnulus.test_array_error_no_effective_gain __________
_________ TestEllipticalAnnulus.test_array_error_array_effective_gain __________

### PR DESCRIPTION
**Pull request by sergiopasra**
This fixes #242 for me

The new if handles the case where the closest point of the triangle is **on** the circle. Then the triangle is outside the circle and the area is 0.0

### CODE REVIEW

**Comment by larrybradley** [comment]
Looks good to me, thanks @sergiopasra!  Anyone else want to review this?

**Comment by bsipocz** [comment]
:+1: 
Many thanks @sergiopasra!

**Comment by cdeil** [comment]
@sergiopasra - Could you please add a one-line entry to `CHANGES.rst`?
We just started that document, but I think it would be good to have this important bugfix listed.

**Comment by sergiopasra** [comment]
Sorry about the git noise... I mistyped the issue number

**Comment by sergiopasra** [comment]
Although this change makes the tests pass in my system, I think there is still something wrong in how the case `in1` is handled. Previously the routine should have computed the are of the very small triangle formed when x1,y1 is inside the circle. Instead, it returned PI

**Comment by cdeil** [comment]
@sergiopasra - Could you please rebase this PR on master?

Can you create a unit test or even a fix for the remaining issue you mentioned in your last comment?
Or file a new issue giving the example and one of us will look into it.

**Comment by cdeil** [comment]
@sergiopasra – Can you please rebase this?

If you don't have time, let me know and I'll rebase and merge this locally.

**Pull request merged**
