### PR TITLE
Adding python 3.6 to CI builds

### PR DESCRIPTION
**Pull request by bsipocz**
Probably we need to wait a bit more until all the dependencies become available on python 3.6.

### CODE REVIEW

**Comment by bsipocz** [comment]
For some weird reason it seems that conda on travis cannot find the scikit-image package, while locally I see it for linux-64: ``scikit-image-0.12.3-np111py36_1``

**Comment by bsipocz** [comment]
OK, so while there are some issues with finding packages there are some real issues with python 3.6, a deprecation with ``inspect.getargspec()``: https://travis-ci.org/astropy/photutils/jobs/187504106#L827

However it is not at all critical as it's in the psf sandbox.

**Comment by bsipocz** [comment]
This PR also removes the numpy prerelease test from the allowed failures (set in #424) as the cause of the halting in the middle of the tests was fixed upstream in ci-helpers. While there are no current prereases, I've tested it with the last one and it indeed worked.

**Comment by bsipocz** [comment]
@larrybradley - This should be ready to go in. I'll leave it open a few more hours in case you want to have a look at it.

**Comment by larrybradley** [comment]
LGTM.  Thanks, @bsipocz!

**Pull request merged**
