### PR TITLE
Revert 1 discrete2 dmodel

### PR DESCRIPTION
**Pull request by mcara**
Tests are failing for SciPy 0.13

### CODE REVIEW

**Comment by mcara** [comment]
@eteq Could you, please, review why are tests failing for scipy 0.13?

**Comment by mcara** [comment]
@eteq Essentially, I am trying to revert changes made by your PR that added tests

**Comment by mcara** [comment]
@eteq Please close this PR without accepting it. I know why it is failing in SciPy 0.13.

I can fix the code to work with SciPy 0.13 but it would be easier if we supported only versions > 0.13.

**Comment by eteq** [comment]
OK, will go ahead and close.  Note that you *should* be able to close pull requests you made yourself, though. 

And it should be no problem to say scipy has to be a more recent version - do you know *how* recent is necessary? (feel free to answer this question in #413 given that I'm closing this - you're continuing to work on that, right?)

**Pull request closed without merging**
