### PR TITLE
Fix normalization for rectangular and elliptical regions

### PR DESCRIPTION
**Pull request by tepickering**
The problem I reported in #265 was due to the pixel normalization being done twice, once in ``rectangular_overlap_single_subpixel`` and again in ``rectangular_overlap_grid``.  I have removed the 2nd one and now the results are what I expected.

### CODE REVIEW

**Comment by larrybradley** [comment]
:+1: Thanks!

**Comment by cdeil** [comment]
@tepickering – Thanks!

Can you cover this bug with a regression test?

**Comment by tepickering** [comment]
ok, i've added tests for ``rectangular_overlap_grid`` to make sure the max mask value is 1.0.  however, i've noticed that there aren't similar tests for the other overlap grid routines.  i'll go ahead and add those, too.

**Comment by tepickering** [comment]
This same bug also exists within ``elliptical_overlap_grid``, however there is another bug there as well that I've described in #277.  I will tackle those in a different PR.

**Comment by tepickering** [comment]
To fix #277, I needed the changes made in #250.  Therefore, I've merged that work into this PR.

**Comment by bsipocz** [comment]
Thanks @tepickering.
I guess cherry-picking #250 would be better than merging, but either way I'm happy to see both bugfix in.

**Comment by larrybradley** [comment]
@tepickering Thanks again for working on this during the SciPy sprints.

**Pull request merged**
