### PR TITLE
Split up psf subpackage more

### PR DESCRIPTION
**Pull request by eteq**
This PR re-organizes some of the machinery in the psf subpackage into separate modules, in preparation for some additional contributions from @mirca and @mcara .

(FYI, @mirca - assuming this PR goes in, you'll probably want to add an additional file and perhaps test file for the grouping stuff whenever you get to adding that to photutils itself.  Or maybe you'll even want multiple modules for e.g. nstar and group - whatever ends up seeming most natural and fits reasonably with this.)

### CODE REVIEW

**Comment by larrybradley** [comment]
I'm merging this now as @mcara would like to start adding his contributions.

**Comment by larrybradley** [comment]
Actually, the test failures here are real (not due to `ci-helpers` issues).  @eteq It looks like you need to update several imports.

**Comment by eteq** [comment]
Oops!  Looks like I forgot to commit the fixes to the tests.  Pushed up now, so hopefully the tests will pass.

**Comment by bsipocz** [comment]
I've restarted travis, you can expect the sphinx build failing, but the fix is coming soon to it. Everything else should pass.

**Comment by eteq** [comment]
the sphinx failures were *real* actually - working on a fix for it

**Comment by bsipocz** [comment]
#380 deals with the ones unrelated to this PR (ValueErrors)

**Comment by eteq** [comment]
I did check locally that the sphinx build succeeded, and now everything else is, so @larrybradley, I think this is ready.

**Comment by bsipocz** [comment]
It seems there are more package version incompatibility, I'll iron them out at the end of today.

**Comment by larrybradley** [comment]
@eteq My only comment is that I'm not a big fan of `photutils/psf/tests/test_misc.py` for miscellaneous tests.  If possible, I would prefer that these tests go in a module named after the module they are testing, i.e. `test_<module>.py`.  I assume there will be further additions and rearranging of the `psf` subpackage soon, so I'll go ahead and merge this now.

**Comment by eteq** [comment]
Ah, I see your point @larrybradley - "misc" has a way of become *everything*...

**Pull request merged**
