### PR TITLE
Add a generic model-based image generator

### PR DESCRIPTION
**Pull request by eteq**
This PR slightly generalizes the machinery in `photutils.datsets` to support generic models rather than just gaussian models.

The proximate use case is for code I regularly re-do in some of the notebooks to mock up PSF-photometry.  More generally, this is going to be useful down the line for doing artificial star tests.  

A couple questions for @larrybradley : I followed the naming scheme of `make_random_gaussians` and `make_gaussian_sources`, but I find that a bit confusing - it's not clear from the names which makes the table, and which makes the "image".  Is there some reason I'm missing for this naming scheme?  And do you think we can change it even if it's a subtle backwards-compatibility break? (Or should we deprecate?)

And a related question: does it make more sense to instead move all of the wcs-ing and such to the `make_noise_image` function?  That way the flow would be something like:
`make_random_*`->`make_*_sources` _>[`make_*_sources` for other models] -> `make_noise_image`, with the WCS options only being added at the end.

### CODE REVIEW

**Comment by larrybradley** [comment]
@eteq  Thanks, I like this!

Regarding the function names, I think for clarity (to be explicit), we'll probably need to use longer function names.  How about something like this?:

`make_gaussian_sources` -> `make_gaussian_sources_image`
`make_random_gaussians` -> `make_random_gaussians_table`

`make_random_models` -> `make_random_models_table`
`make_model_sources` -> `make_model_sources_image`

I'm open to other suggestions.

For the WCS stuff, I'm pretty sure I didn't add that.  My proposal would be to remove all of the WCS/hdu/header stuff from these functions and put it all into a single, separate function.  The current functions would simply return ndarrays, but *if* you want WCS too then use this (new) other function to do it.  That we don't have to keep repeating the same WCS/hdu/header parameters and boilerplate in every new `make_*` function.  Sound good?

**Comment by bsipocz** [comment]
The wcs/hdu stuff was added in #203 with the aim to avoid using remote data for testing aperture photometry. 
Having them moved out to a separate single function sounds great to me.

**Comment by eteq** [comment]
I'm happy with those name changes, @larrybradley!

**Comment by larrybradley** [comment]
@bsipocz `CircleCI` is failing in `astropy-helpers` during `import numpy`:

File "/home/ubuntu/photutils/astropy_helpers/astropy_helpers/utils.py", line 94, in get_numpy_include_path
    import numpy
ImportError: No module named numpy

Have you seen this `astropy-helpers` error before?  It's strange that it is failing now because I don't see where anything changed.

**Pull request merged**
