### PR TITLE
Changing parametrized tests to be pytest 3.2.0 compatible

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by larrybradley** [comment]
The python 3.4 test fails because it's using pytest 3.0.5, which apparently does not have the `pytest.param` fixture.

I think the best workaround for now is simply to limit the pytest version to < 3.2.

**Comment by bsipocz** [comment]
I can build a pytest 3.1 version for py3.4 in the astropy-ci-extras channel.

**Comment by larrybradley** [comment]
@bsipocz I just reran the failing py3.4 test and it it still using pytest 3.0.5 (and thus still failing).  Ping!

**Comment by bsipocz** [comment]
@larrybradley - Yes, we run into troubles there with the machinery, I can only forward the ping to @mwcraig as he's the only one with a full understanding of our conda infrastructure.
https://github.com/astropy/conda-channel-ci-extras/pull/22

**Comment by larrybradley** [comment]
As a temporary workaround could I install an updated pytest via pip?  Or perhaps we should drop the  py3.4 test?

**Comment by mwcraig** [comment]
> As a temporary workaround could I install an updated pytest via pip? 

That should work.

I'll *try* to take a look at the underlying issue tonight...

**Comment by larrybradley** [comment]
I installed pytest >= 3.1 via pip as a workaround.  Thanks, @bsipocz!

**Pull request merged**
