### PR TITLE
More robust version checking

### PR DESCRIPTION
**Pull request by larrybradley**
This PR uses `LooseVersion` for more robust and simpler version checking.

### CODE REVIEW

**Comment by bsipocz** [comment]
:+1: 
thanks @larrybradley for crossing off things from my todo list :)

**Comment by bsipocz** [comment]
@larrybradley - The travis failure is totally unrelated and due to a conda issue I'm fixing in ``ci-helpers`` atm. When that one is in I meant to merge this.

**Comment by larrybradley** [comment]
@bsipocz Thanks, I was just trying to figure out what was going on with that test (it's failing on my other PR too).  I thought it was a transient failure, but I quickly discovered that it wasn't.

**Comment by bsipocz** [comment]
@larrybradley - Hmm, it wasn't the silly install WARNING that got picked up. The only remaining warning is the matplolib one https://travis-ci.org/astropy/photutils/jobs/101686421#L521 but those usually don't trigger sphinx fails.

**Comment by larrybradley** [comment]
I have no idea why that is triggering the failure either.  I suspect the `matplotlib` font cache warning is due to `matplotlib 1.5.1` which was released two days ago, but I don't know how to fix it.

**Comment by bsipocz** [comment]
What about trying to fix the version number to 1.5.0 for now?

**Comment by larrybradley** [comment]
Thanks, I'll try that.

**Comment by astrofrog** [comment]
Had the same issue in Glue, need to fix Matplotlib to 1.5.0 - see https://github.com/glue-viz/glue/pull/821#issuecomment-170864568

**Comment by astrofrog** [comment]
But it's not a long term solution :(

**Comment by larrybradley** [comment]
Thanks, @astrofrog.  Hopefully they fix this issue in the next `matplotlib` release.

**Comment by larrybradley** [comment]
@bsipocz Why is the `build_sphinx` test using `Python 3.4` instead of `3.5`?  Does `3.5` not work?

**Comment by bsipocz** [comment]
@larrybradley -  I don't find any trace of a reason for it, most probably it was as overlook.

**Comment by larrybradley** [comment]
`matplotlib 1.5.0` conflicts with `python 3.3` in `conda` (https://travis-ci.org/astropy/photutils/jobs/101925006#L419).  So, I'll have to use `pip` for `matplotlib`.

**Comment by larrybradley** [comment]
Is there a way to specify a maximum version in `conda` (like `conda install matplotlib<=1.5.0`, which doesn't work)?

**Comment by bsipocz** [comment]
@larrybradley - Let's see how much slower the pip solution is. If significant, then I suggest to fix the version number only for the sphinx builds (as those are the only affected builds) and use the latest from conda for the rest.
Not sure that one can say the maximum version number, but what about saying ``matplotlib=1.5.0``? It shouldn't install a newer version, I think.

**Comment by larrybradley** [comment]
I tried `matplotlib=1.5.0` but the install failed because of a conflict with `python 3.3`:
https://travis-ci.org/astropy/photutils/jobs/101925006#L419

It appears `matplotlib 1.5.0` is no longer available with `python 3.3`.

**Comment by bsipocz** [comment]
Sorry, what I meant was to have this:
```
        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - python: 2.7
          env: ASTROPY_VERSION=development SETUP_CMD='build_sphinx -w'
                  CONDA_DEPENDENCIES='Cython scipy scikit-image matplotlib=1.5.0'
        - python: 3.4
          env: ASTROPY_VERSION=development SETUP_CMD='build_sphinx -w'
                  CONDA_DEPENDENCIES='Cython scipy scikit-image matplotlib=1.5.0'
```

**Comment by larrybradley** [comment]
Ah, yes that's probably what I should have done at the start instead of changing the global `matplotlib` dependency.  Thanks! :smile:

**Comment by larrybradley** [comment]
@bsipocz I tried fixing `matplotlib=1.5.0` for only the Sphinx builds.  `matplotlib 1.5.0` does get installed, but then it gets updated to `1.5.1` (see https://travis-ci.org/astropy/photutils/jobs/101941930#L495).  Do you know what's going on?  Feel free to open a new PR if you can fix matplotlib to 1.5.0.  You may have better luck than me. :smiley:

**Comment by larrybradley** [comment]
The fix is now upstream in `ci-helpers` (https://github.com/astropy/ci-helpers/pull/41).

**Comment by larrybradley** [comment]
I'm going to merge this.  The test failure is due to an errant warning being issued by `matplotlib 1.5.1` -- it will fail until the `matplotlib` version is fixed to `1.5.0` in `ci-helpers`.

**Pull request merged**
