### PR TITLE
MNT: Set max-line-length for flake8

### PR DESCRIPTION
**Pull request by pllim**
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.

### CODE REVIEW

**Comment by larrybradley** [comment]
Our `pep8speaks` bot is already using 79 chars (you made that commit) :).

**Comment by pllim** [comment]
I thought @bsipocz wanted 100? Heh heh.

🤖 vs 😃

**Comment by larrybradley** [comment]
It's Westworld!

**Comment by pllim** [comment]
"Am I... me?"

**Comment by bsipocz** [comment]
Don't fix what's not broken, there is no need for a change here.

**Pull request closed without merging**
