### PR TITLE
Changing rtd configs to use conda

### PR DESCRIPTION
**Pull request by bsipocz**
This may be enough to fix the current rtd fails. If not I'll add a mpl version requirement, too.

### CODE REVIEW

**Comment by bsipocz** [comment]
@larrybradley - It seems that it's not possible to set multiple e-mail addresses to receive notifications from RTD build fails. Currently they are sent to your gmail address. Could you please set up a filter to fwd them to me, too?

**Comment by larrybradley** [comment]
@bsipocz From the RTD admin panel, it looks like your gmail address should be receiving failure notifications.  Is that not working (perhaps check your "Spam" folder)?

**Comment by larrybradley** [comment]
BTW, the current RTD failures appear to be only for the PDF version of the docs (#393).  You can test this locally by running `make latexpdf` in the docs directory.

**Comment by bsipocz** [comment]
I've just added that address now, and misread the dropdown stuff underneath. Sorry for the noise.

**Comment by bsipocz** [comment]
There is another fail (that only gives warnings, so not trivial to spot). For the html builds, none of the new plots show up for the grouping page as the cmap is viridis, but rtd installs an old mpl, so it's not available.
Anyway, I think that installing the dependencies from conda should be slightly faster, and astropy already uses this approach.

**Comment by bsipocz** [comment]
@mirca @hamogu - This indeed fixed the plots here http://photutils.readthedocs.io/en/latest/photutils/grouping.html

**Pull request merged**
