### PR TITLE
[DOC]: sigclip_iters should be int rather than float

### PR DESCRIPTION
**Pull request by mirca**
Just fixing a minor typo in the docstring.

### CODE REVIEW

**Comment by bsipocz** [comment]
Travis failures are due to #357. This can be merged, but ideally we should aim for a quick fix for that and then merge it without breaking master.

**Comment by bsipocz** [comment]
@larrybradley - I've merged this as the failures went away locally, and rerunning travis seemed an overkill.

**Comment by larrybradley** [comment]
Thanks, @bsipocz.  This was just a minor doc change, so no need to rerun `travis`.  `travis` will run on the merge commit to master anyway (which will test if everything is OK with the upstream fix).

**Comment by bsipocz** [comment]
Yes, that was my train of thoughts, too.

**Pull request merged**
