### PR TITLE
Fix checks on oversampling

### PR DESCRIPTION
**Pull request by larrybradley**
@olebole Can you please check if this fixes your issues in #1085?

### CODE REVIEW

**Comment by larrybradley** [comment]
@olebole If this fixes the issue, then I can make a quick 1.0.1 release.

**Comment by olebole** [comment]
Yes, this [fixes the build time tests](https://buildd.debian.org/status/logs.php?pkg=photutils&ver=1.0.0-2&suite=sid) for all architectures (at least the official ones; the other are still building). 

Thank you for the prompt fix! Shall I close #1085?

**Comment by larrybradley** [comment]
@olebole Can you let me know when the other builds are complete?  If everything passes, I'll do a 1.0.1 release.  Thanks.

**Comment by olebole** [comment]
All builds were [completed and successfull](https://buildd.debian.org/status/logs.php?pkg=photutils&ver=1.0.0-2&suite=sid). So I am really fine with it. Thanks!

**Comment by larrybradley** [comment]
Thanks so much!

**Pull request merged**
