### PR TITLE
Misc PEP8 cleanup in psf subpackage

### PR DESCRIPTION
**Pull request by larrybradley**
CC: @Onoddil, @eteq

### CODE REVIEW

**Comment by bsipocz** [comment]
Would it make sense to tighten the flake8 tests on travis?

**Comment by larrybradley** [comment]
Yes, good idea.  Instead of selecting only a few, we should probably start with everything and only add ignore items as necessary.

**Comment by bsipocz** [comment]
Originally, as I recall, it only tested for a selected set as some maintainers thought it keeps the bar of entry lower. I'm not sure whether that is true or false.
For astroquery we instead use the pep8speak bot that comments about all but a few ignored ones, but the travis job is running only for a few selected (rather than all but a few ignored) ones. It works nicely, folks keeping cleaning up their PRs based on the bots input. Whether they find it friendly or not, I'm not sure about.

**Comment by larrybradley** [comment]
The pep8speak bot sounds interesting.  I'll check it out.  In the meantime I won't update the flake8 rules in travis yet.  I'm just running a quick code-check pass before release.

**Comment by larrybradley** [comment]
Our current flake8 tests are rather minimal.

**Comment by bsipocz** [comment]
Before opting in the bot I would ask your local (e.g. mast) folks informally how much they hated to have it on astroquery, is it useful or only annoying.

**Comment by larrybradley** [comment]
IMHO, the bot looks very useful, especially for beginners.  Otherwise, a maintainer will have to go digging in the travis log to see the flake8 failures and then report back.  Automation for the win? 🤖 🤖 🤖

**Comment by bsipocz** [comment]
Yes, I love the bot exactly for those reasons, but I might be in the minority as overall I like the bots 😅

**Comment by larrybradley** [comment]
I, for one, welcome our new robot overlords.

**Pull request merged**
