### PR TITLE
Some fix for psf modeling

### PR DESCRIPTION
**Pull request by bsipocz**
First of all, there were tons of broken API links, not sure how those passed the docs build test.

### CODE REVIEW

**Comment by bsipocz** [comment]
(I'm not sure it will fix the RTD build, but now at least I can build the docs locally).

**Comment by bsipocz** [comment]
Given that travis has passed for astropy-dev, I've pushed another commit that reverts #928 with skip-ci, given that everything is nice prior to that.

**Comment by bsipocz** [comment]
Let's hope that this will fix the RTD failure. I don't exactly see why it would, but neither see why it's failing.

**Comment by larrybradley** [comment]
RTD is still failing.

**Comment by bsipocz** [comment]
Bummer.

Something is not right with the docs build test either. I can't see how these many failing API links could pass it, while I locally got the warning, prior this PR e.g. 
```
Warning, treated as error:
/Users/bsipocz/munka/devel/photutils/build/lib.macosx-10.13-x86_64-3.7/photutils/psf/models.py:docstring of photutils.EPSFModel.origin:11:py:obj reference target not found: x_0
Sphinx Documentation subprocess failed with return code 2
```

**Comment by larrybradley** [comment]
I have no idea how the docs build test didn't fail with this many broken API links either.  It's usually very strict.

Are you building the docs with astropy 3.2.1 or master?

**Comment by bsipocz** [comment]
I was building it with master. Good point, maybe should check on it prior this PR with 3.2.1, what happens to those links.

**Comment by bsipocz** [comment]
Ahh, ok. So these were treated as attributes rather than parameters, and thus got documented. So I might overdone their commenting out here a bit, but as I said this fix is ugly 🤷‍♀

**Pull request merged**
