### PR TITLE
(Re)added functionality to process datacubes. Includes testing. Rebas…

### PR DESCRIPTION
**Pull request by fdeugenio**
Added functionality to do aperture photometry on datacubes. This is useful to create single aperture or slit spectra from an integral field spectroscopy datacube.

Rebased on most recent master as per @larrybradley 's comment. Passes all local tests.

### CODE REVIEW

**Comment by fdeugenio** [comment]
Okay, a python2.7 compatibility issue.

**Comment by fdeugenio** [comment]
FIxed the issue, resubmitting.

**Comment by larrybradley** [comment]
@fdeugenio There's no need to close and create a new PR.  You can simply (force) push to your branch and the existing PR will be updated.

**Comment by fdeugenio** [comment]
Yes I realised that at some point, when I looked at a PR I had just closed and seen the latest commit was already in there. Apologies if this caused clutter and/or additional work on your behalf.

**Pull request closed without merging**
