### PR TITLE
Ability to import and use HST/JWST STDPSF-format ePSFs

### PR DESCRIPTION
**Pull request by mperrin**
As discussed on slack with @larrybradley and others. This code adds an ability to read in and convert to GriddedPSFModel instances the ePSFs for HST and JWST created by Jay Anderson and collaborators, in the semi-undocumented "STDPSF" format FITS files as created by Jay's tools in Fortran. 

Draft PR, to be available for discussion in a meeting later today. 

To do: 

- [ ] Documentation
- [ ] Unit test(s)
- [ ] Tests with PSF fitting in photutils using such ePSFs on HST and/or JWST data.
- [ ] Continued discussion TBD on interfaces and integration

### CODE REVIEW

**Comment by mperrin** [comment]
Example code demonstrating import of STDPSF files, reproducing part of Fig 4 of [Libralatto et al. 2023](https://arxiv.org/pdf/2303.00009.pdf): 

```
stdpsf = STDPSFGrid('NIRISS/STDPSF_NIRISS_F090W.fits')
stdpsf.display_grid(show_deltas=True, percent_norm=True)

griddedmodel = stdpsf.to_griddedpsfmodel()
```
Unknown-5

**Comment by mperrin** [comment]
I'm trying to remember the status of this after last month. I think it's ready so am going to move it from Draft to Ready for Review now.

**Comment by mperrin** [comment]
Still ought to add some documentation to this. 

Not as sure what to do about the unit tests, since that would start to introduce dependencies on external data files for testing that. Would like input from @larrybradley or others about how the CI is set up for photutils already and whether or not you have a suite of data files for the CI, into which we could insert some example JWST ePSF file for use in testing. Thoughts?

**Comment by larrybradley** [comment]
@mperrin Could you mock up a STDPSF FITS file that has very small PSF arrays and use that for tests?  I don't want to put a large FITS file in the repo.

**Comment by mperrin** [comment]
@larrybradley I don't have the code to create STDPSF files myself. I could perhaps mock something up in ad hoc code, but it would be better to use a small example made with the actual official code, to ensure all the details are correct & consistent. So it would probably be better to ask Jay or Mattia to make such a file.

**Comment by larrybradley** [comment]
Here's a small (8.5k) mocked version of a STDPSF file that can go in the repo:
https://www.stsci.edu/~lbradley/STDPSF_WFC3UV_F814W_mock.fits

To make this file I simply shrunk the internal data arrays.  The mocked file should be able to read with this `STDPSFGrid` class and is fine for testing.  You could also add a "remote-data" test for real STDPSF files by loading the data from a URL, e.g., https://www.stsci.edu/files/live/sites/www/files/home/hst/instrumentation/wfc3/data-analysis/psf/_documents/PSFSTD_WFC3IR_F105W.fits.

I assume such a URL is persistent.

**Pull request merged**
