### PR TITLE
correcting upper harmonics (and related errors)

### PR DESCRIPTION
**Pull request by shivangeerathi**
The upper harmonics and related errors are corrected. (`scipy.optimize.leastsq()` returns the inverse of Hessian matrix) 
Was previously discussed in #1004 and #1008.

### CODE REVIEW

**Comment by larrybradley** [comment]
ping @ibusko

**Comment by larrybradley** [comment]
@ibusko?

**Comment by ibusko** [comment]
Looks good to me.

**Comment by larrybradley** [comment]
Thanks, @shivangeerathi.  This PR causes this test to fail:  https://travis-ci.org/github/astropy/photutils/jobs/731908442#L517.  `a3, b3, a4, b4, a3_err, b3_err, a4_err`, and `b4_err` are all `None`.

It also breaks this example notebook (see last plot):
https://github.com/astropy/photutils-datasets/blob/master/notebooks/isophote/isophote_example2.ipynb

And this one too (after cell 19):
https://github.com/astropy/photutils-datasets/blob/master/notebooks/isophote/isophote_example4.ipynb

Also, the results from this notebook are significantly different:
https://github.com/astropy/photutils-datasets/blob/master/notebooks/isophote/isophote_example3.ipynb

CC: @ibusko

**Comment by shivangeerathi** [comment]
@larrybradley, thanks for pointing it out, there was indeed some mistake in the previous corrections. I checked, in isophote_example2.ipynb, it gives out reasonable values for upper harmonics.

**Comment by larrybradley** [comment]
@ibusko Can you please review these updates?

**Review by larrybradley — APPROVED** [review]
Thanks, @shivangeerathi!

**Pull request merged**
