### PR TITLE
Apply correct shift in prepare_psf_model

### PR DESCRIPTION
**Pull request by krachyon**
With regards to issue #1163 I'm now reasonably sure that the model to fit the EPSF to a star in EPSF photometry needs to be inverted. 
This seemed to produce sensible results in multiple trials on simulated and real images, while the original shift produces results indistinguishable from just running the respective starfinder on the image.

### CODE REVIEW

**Comment by krachyon** [comment]
> Hello @krachyon! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:
> 
>     * In the file [`photutils/psf/tests/test_photometry.py`](https://github.com/astropy/photutils/blob/90cbfaf479872a95f87e4792e3c51f9aa643f8fd/photutils/psf/tests/test_photometry.py):
> 
> 
> > [Line 841:31](https://github.com/astropy/photutils/blob/90cbfaf479872a95f87e4792e3c51f9aa643f8fd/photutils/psf/tests/test_photometry.py#L841): [E241](https://duckduckgo.com/?q=pep8%20E241) multiple spaces after ','
> > [Line 847:15](https://github.com/astropy/photutils/blob/90cbfaf479872a95f87e4792e3c51f9aa643f8fd/photutils/psf/tests/test_photometry.py#L847): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> > [Line 848:17](https://github.com/astropy/photutils/blob/90cbfaf479872a95f87e4792e3c51f9aa643f8fd/photutils/psf/tests/test_photometry.py#L848): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> > [Line 848:30](https://github.com/astropy/photutils/blob/90cbfaf479872a95f87e4792e3c51f9aa643f8fd/photutils/psf/tests/test_photometry.py#L848): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> > [Line 849:17](https://github.com/astropy/photutils/blob/90cbfaf479872a95f87e4792e3c51f9aa643f8fd/photutils/psf/tests/test_photometry.py#L849): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> > [Line 850:28](https://github.com/astropy/photutils/blob/90cbfaf479872a95f87e4792e3c51f9aa643f8fd/photutils/psf/tests/test_photometry.py#L850): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> 
> ##### Comment last updated at 2021-04-03 17:47:10 UTC

Imho the referenced code block looks much worse formatted "properly". Is there a way to turn of style checks for these lines?

**Review by larrybradley — APPROVED** [review]
Many thanks, @krachyon.  Yes, this was bug in `prepare_psf_model`.  I went ahead and updated the PR because I want to get this in the 1.2 release.

Note that `prepare_psf_model` is not needed  (or recommended) for an `EPSFModel`.  `EPSFModel` (and any model with `x_0`, `y_0`, and `flux` parameters) can be input directly to the photometry classes.

**Comment by krachyon** [comment]
> Note that `prepare_psf_model` is not needed (or recommended) for an `EPSFModel`. `EPSFModel` (and any model with `x_0`, `y_0`, and `flux` parameters) can be input directly to the photometry classes.

I was a bit unsure about that originally, `prepare_epsf_model` felt and feels a bit magic in what it's supposed to do. Maybe adding something like 
"Does not need to be called on EPSFModel. Only needed for models without spatial parameters or to mark the parameters corresponding to x and y shifts."
To the docstring would clear it up for others...

**Comment by larrybradley** [comment]
Yes, I was thinking the same. I updated the docstring here: #1253

**Pull request merged**
