### PR TITLE
rm extra 'you'

### PR DESCRIPTION
**Pull request by Gabriel-p**
very small fix

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @Gabriel-p! 

Could you please add ``[skip ci]`` to the commit messages for pure docs typo fixes, so we don't run CI unnecessarily?

**Comment by Gabriel-p** [comment]
@bsipocz of course, I didn't know that could be done. Thanks.

**Comment by bsipocz** [comment]
yes, it's a generic one that can be used in any repository as CI natively understands. We also have a few additional ones of our own that can be used in repos that uses ``ci-helpers``, e.g. ``[docs only]`` and ``[travis skip]`` that will only run the docs build, or skip CI on travis.

**Comment by Gabriel-p** [comment]
I'm trying the PSF photometry classes on a crowded field, so I'll probably be pushing small fixes to the docs like this one. Please let me know if I screw anything up. Thanks!

**Comment by bsipocz** [comment]
Sounds good. If you expect to have multiple fixes, then I suggest to put them all in one PR (you can still extend that incrementally, just let us know so we don't merge it prematurely).

**Pull request merged**
