### PR TITLE
Clean up psf sub-package in preparation for v0.4

### PR DESCRIPTION
**Pull request by mirca**
Small clean up towards v0.4 release.

### CODE REVIEW

**Comment by bsipocz** [comment]
This will need CI running on it once we updated the travis matrix to test only with astropy 2.0

**Comment by larrybradley** [comment]
Thanks, @mirca.  Yep, can't really merge this until after astropy 2.0 is released and the CI scripts have been updated.

**Comment by mirca** [comment]
@bsipocz @larrybradley Yup! That's why I skip ci =)

**Comment by larrybradley** [comment]
@mirca Can you repush this commit without the `skip ci`?  I think the `ci-helpers` use `astropy 2.0` for the `lts` version now, so this should pass.

**Comment by bsipocz** [comment]
Yes, LTS==astropy2.0, and actually is now terminated once it realizes that stable and lts are equal to avoid wasting CI time by double testing.

**Comment by mirca** [comment]
@bsipocz @larrybradley looks like failures here are unrelated to this (?)

**Comment by larrybradley** [comment]
@mirca I don't see any failures (all green!).  Merging, thanks!

**Pull request merged**
