### PR TITLE
Improve performance of ellipse fitting

### PR DESCRIPTION
**Pull request by ibusko**
This comes from work discussed in issue #802. 

In a nutshell, when profiling the code, we found  that vectorization of the `geometry.to_polar` method caused a significant performance degradation. In this PR we modify `to_polar` so it can handle scalar input quantities using scalar code, but still keeping its vectorized habilities. 

Profiling analysis indicates that the code returned to its overal performance level, similar to we had before.

Due to its own nature, the ellipse fitting algorithm as originally coded is slow. We are still investigating other approaches that involve a more in-depth vectorization of the entire algorithm, or caching of intermediate data (or both). This PR is to be taken as a stopgap solution to a pressing problem.

We tested this using both the test code provided in #802, as well as the notebook tutorials in `photutils-datasets`.

### CODE REVIEW

**Comment by larrybradley** [comment]
CC @moustakas

**Comment by moustakas** [comment]
Thank you, @ibusko!

I tested the pip-installed `photutils/v0.6` against the branch in this PR (`0.7.dev3364`) and indeed found a a factor of ~5 speed-up.  Nice!

I also made sure that the ellipse-fitting results are identical (not just the intensity, all attributes of the `IsophoteList` object) and indeed they are -- please feel free to merge this PR and close #802.  (If I have any further suggestions for improving the performance I'll open a new issue.)

**Comment by larrybradley** [comment]
Thanks, @ibusko!  And thanks, @moustakas for testing the PR!

**Comment by larrybradley** [comment]
Changelog entry added here: https://github.com/astropy/photutils/commit/19d92c86d5d6f0ee85e88b0eacdac6377b578eb3

**Pull request merged**
