### PR TITLE
Using system pytest rather than astropy bundled

### PR DESCRIPTION
**Pull request by bsipocz**
astropy core is considering removing the bundled pytest (see https://github.com/astropy/astropy/issues/5509), so I use photutils to see how badly this idea affect affiliates (e.g. we may see pytest 3.0.x related failures).

### CODE REVIEW

**Comment by larrybradley** [comment]
Thanks, @bsipocz.  Many `travis` tests are failing with "Fetching package metadata ...An unexpected error has occurred, please consider sending the following traceback to the conda GitHub issue tracker at:...".  Is this a conda version mismatch issue?

**Comment by bsipocz** [comment]
@larrybradley - I've never seen that before, will investigate later today.

**Comment by bsipocz** [comment]
It seems that restarting the build will solve the issue (it worked for one build, now restarted all of them).

**Comment by larrybradley** [comment]
Thanks.  All checks have passed now.

**Comment by bsipocz** [comment]
Do you think we need to add pytest to the requirements and thus changelog or is it coming with python by default?

**Comment by larrybradley** [comment]
In the installation docs we state that `photutils.test()` is a way to run the tests for an installed version, so at the very least we also should mention there that `pytest` is required to run the tests. Since `pytest` is required only to run the tests, I'm not sure if we should formally make it a package requirement or not.  What will `astropy` do?  :smile:

**Comment by bsipocz** [comment]
The last commit here should fix the unittest issue we see in #532. So we either go ahead and merge this (I think it shouldn't matter whether upstream astropy/astropy#5509 gets merged or not), or that commit can be cherry-picked into that PR.

**Comment by bsipocz** [comment]
astropy LTS is not compatible with pytest3 (https://github.com/astropy/astropy/issues/4607#issuecomment-289927625), so I've changed it to run with python3.5

**Comment by bsipocz** [comment]
@larrybradley - Should we go ahead with this? Having pytest3 would solve tons of failures in #532.

**Comment by larrybradley** [comment]
@bsipocz Yes, let's go ahead with this.  Many thanks!

**Comment by bsipocz** [comment]
It may not work with LTS, that case we will need to limit astropy's version for isophot testing. I'll keep an eye on CI here and in the other PR, too.

**Comment by bsipocz** [comment]
This is now depends on astropyci-helpers#184

**Comment by larrybradley** [comment]
@bsipocz I fixed the biweight failures, so if you rebase this it should pass now.

**Comment by larrybradley** [comment]
@bsipocz Is this ready to merge?

**Pull request merged**
