### PR TITLE
Adding np 1.11 to the travis matrix

### PR DESCRIPTION
**Pull request by bsipocz**
as the latest stable is 1.12

@larrybradley - What do you think about dropping np1.7 at some point?

### CODE REVIEW

**Comment by larrybradley** [comment]
@bsipocz That sounds good to me!  Astropy should probably drop np 1.7 too.

**Comment by bsipocz** [comment]
Great, I'll drop it here then. Should I mention it in the changelog? While it may work in the future, we can't really guarantee it.
 
I'm also fixing the LTS issues.

**Comment by larrybradley** [comment]
Sure, add it in the changelog.  Also, the requirements section on install page needs to be updated:
http://photutils.readthedocs.io/en/latest/photutils/install.html

Thanks, @bsipocz!

**Comment by bsipocz** [comment]
should it be 0.4, or can we do that in 0.3.1?

**Comment by larrybradley** [comment]
I think 0.3.1 is fine.  It's not a new feature.

**Comment by bsipocz** [comment]
@larrybradley  @astrofrog - Is it normal that the circleci build picks up numpy 1.8 and astropy 1.2.1? According to the docker image, it should be pip installing astropy, so I assume that should pick up astropy 1.3?

**Comment by larrybradley** [comment]
@bsipocz The docker images that get pulled are static (they don't get continuously built from the Dockerfile).  They need to be manually rebuilt and pushed to Docker Hub.  I can rebuild them locally (and indeed astropy 1.3 is now installed), but I don't have permission to push them up to the astropy docker hub account.  @astrofrog will need to do that or give me permission.

**Pull request merged**
