### PR TITLE
Change travis install of astropy from conda to pip

### PR DESCRIPTION
**Pull request by bsipocz**
Changing the way of the astropy install should act as a workaround #274, while we track down a fix for that. 
I've changed the aperture tests that triggered the failures leading to the discovery this issue.

### CODE REVIEW

**Comment by astrofrog** [comment]
@bsipocz - just out of curiosity, have you tried specifying ``astropy=1.0.3`` to see if it gives an error? (with conda)

**Comment by bsipocz** [comment]
I just did it. And it fails. (And also realized that it worked on RHEL before as the numpy version was left on 1.9, rather than 1.8). 
```
(test)bsipocz@apm36:~/conda_test$ $CONDA_INSTALL numpy=1.8 astropy=1.0.3
Fetching package metadata: ......
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|###########################################################################################| 100%


Hint: the following packages conflict with each other:
  - numpy 1.8*
  - astropy 1.0.3*

Use 'conda info numpy' etc. to see the dependencies for each package.
```

**Comment by bsipocz** [comment]
So it seems I shouldn't have open the travis issue either.

**Comment by bsipocz** [comment]
@larrybradley, @astrofrog - This passes (the failure is due to the matplotlib version issue). Do you have anything against this workaround?

**Comment by larrybradley** [comment]
Looks fine to me.  We should probably do the same for `matplotlib`.

**Comment by bsipocz** [comment]
Sure, I don't mind using pip at all.
However using conda locally with numpy=1.7 works fine for matplotlib, so it
should be a bit different issue.

```
conda install matplotlib numpy=1.7Fetching package metadata: ....
Solving package specifications: .......................
# All requested packages already installed.
# packages in environment at /home/bsipocz/miniconda/envs/test:
#
matplotlib                1.3.1                np17py27_0
numpy                     1.7.1                    py27_2
```

**Comment by bsipocz** [comment]
I think this is good to go, all but one travis run passes and the one failed du to an unrelated timeout (I've restarted it).

**Comment by mwcraig** [comment]
@bsipocz @larrybradley -- I've uploaded builds of matplotlib 1.4.3 and astropy 1.0.3 to astropy-ci-extras if you want to switch back to that.  Will work in the next couple of weeks on automating that to some extent.

**Comment by bsipocz** [comment]
Thanks @mwcraig. 

@larrybradley - I leave this to you, as personally I have nothing against ``pip``, but maybe there are some considerations I'm not aware that we should prefer ``conda``.

**Comment by larrybradley** [comment]
Thanks, @mwcraig!  @astrofrog Do you recommend switching back to `conda`?

**Pull request merged**
