### PR TITLE
Removable of unused and memory intense ePSF iteration save states

### PR DESCRIPTION
**Pull request by Onoddil**
Minor pull request to fix memory issues with `EPSFBuilder`, removing variables which save snapshots of various things in each loop, which increased in usage as a result of refactoring to the ePSF framework in #817. Other ancillary and unused variables were removed at the same time.

I wasn't 100% sure what 'type' the changelog should be under so I just put the change in the 'other' section for now, but feel free to move it (or ask me to move it) if it's better suited to another changelog section.

cc @larrybradley

### CODE REVIEW

**Comment by larrybradley** [comment]
I would remove the change log entry.  We don't typically announce changes to private variables.

**Comment by Onoddil** [comment]
That's what I was wondering really; either way, I have undone the changelog commit.

**Comment by bsipocz** [comment]
@Onoddil - rule of thumb: we changelog things that are exposed to users, e.g. via the API docs. Thus no changelog for PRs for docs updates, internal refactorings, infrastructure aimed for photutils only, tests, and devops.

**Comment by larrybradley** [comment]
I'm very happy to report that RTD builds are passing again.  Thanks.

**Pull request merged**
