### PR TITLE
Updating astropy_helpers to v3.1

### PR DESCRIPTION
**Pull request by bsipocz**
~Don't yet merge, it's opened for testing and needs to be updated to point to the actual release when it's released.~

This should be merged now when CI is green.

### CODE REVIEW

**Comment by bsipocz** [comment]
Merging as this is now all green. Thanks for the patience!

**Comment by larrybradley** [comment]
No worries.  Should we keep the `DEBUG=True`?

**Comment by bsipocz** [comment]
Until travis runs out of lines to display it won't hurt, but feel free to remove.

**Comment by larrybradley** [comment]
OK, I'll keep for now.

**Pull request merged**
