### PR TITLE
Enable AppVeyor Windows CI testing

### PR DESCRIPTION
**Pull request by larrybradley**
Implements #220.

### CODE REVIEW

**Comment by larrybradley** [comment]
The AppVeyor tests have been running for a day now.  They shouldn't be taking this long.  @astrofrog, can you cancel the "1.0.2" test and try restarting the "1.0.3" test?

**Comment by astrofrog** [comment]
@larrybradley - done. If you create an appveyor account @mwcraig can add you as an admin (since photutils is also under the astropy account)

**Comment by larrybradley** [comment]
@mwcraig  My appveyor username is `larrybradley` (I simply connected my github account).  Thanks!

**Comment by mwcraig** [comment]
@larrybradley -- you should be able to control jobs now. photutils looks awesome, by the way, excited about trying it out!

**Comment by larrybradley** [comment]
Thanks, @mwcraig!

**Comment by cdeil** [comment]
So is this now active? If yes, could you please put a status shield into the README next to the one from travis-ci so that it's easy to find?

**Comment by larrybradley** [comment]
Yep, will do!

**Comment by larrybradley** [comment]
Done in https://github.com/astropy/photutils/commit/371b65a7809529c4d1dd4406fc480182bd0cc33d.

**Pull request merged**
