### PR TITLE
MNT: Ignore import error in pytest collection

### PR DESCRIPTION
**Pull request by pllim**
This is an automated update made by the `batchpr` tool :robot: to future-proof test collection behavior `pytest-doctestplus` - feel free to close if it doesn't look good or isn't relevant! You can report issues to @pllim.

### CODE REVIEW

**Comment by larrybradley** [comment]
Thankfully, we don't have any import errors.

**Comment by pllim** [comment]
You might if we remove the hack in doctestplus in the future.

**Comment by bsipocz** [comment]
hopefully we only remove it when https://github.com/astropy/pytest-doctestplus/issues/110 is addressed, so if needed we can go ahead with that. But even then, photutils I suppose won't have much problems.

**Comment by larrybradley** [comment]
I don't think there any any import errors in `photutils`.  But if there are, then I want to know about them. :smile:

**Comment by bsipocz** [comment]
(there wasn't any neither here nor in astroquery when I tested a few things and experimental hacks in the plugin prior its latest release).

**Pull request closed without merging**
