### PR TITLE
`DiscretePRF.create_from_image`: raise a helpful error if the subsampling parameter is too high

### PR DESCRIPTION
**Pull request by barentsen**
I started playing around with the PSF photometry functions.  A minor annoyance is that `DiscretePRF.create_from_image` yields an unclear error message when the `subsampling` parameter is set too high, namely:

```
ValueError: need at least one array to concatenate
```

This PR suggests a more helpful error message, namely:
```
ValueError: The source coordinates do not sample all sub-pixel positions. Reduce the value of the subsampling parameter.
```

Note that both `photutils/psf/models.py` and `photutils/psf/sandbox.py` implement an identical version of `DiscretePRF`.  I have edited the one in `photutils/psf/sandbox.py` because that's the one currently being imported in `photutils/psf/tests/test_psf_photometry.py`, but we should really get rid of one?!

### CODE REVIEW

**Comment by bsipocz** [comment]
Thanks @barentsen. Ping @mirca to comment on sandbox, do we still need it?

**Comment by bsipocz** [comment]
@larrybradley - I've milestoned this to 0.3 as being trivial improvement and didn't merged yet only as it would be great to clear up sandbox question and remove it if it's indeed not needed any more.

**Comment by mirca** [comment]
@bsipocz I'm not sure. I think the one in `models.py` should be removed. But let's see what @eteq thinks.

**Comment by eteq** [comment]
First a question for @barentsen : did you recognize from the name or docs or whatever that this functionality is in the "sandbox" meaning something like "experimental, may go away because it still needs work" (or in this case "was written with an earlier less-designed version")?

So the corollary is that yes, definitely it should get pulled from models...

**Comment by barentsen** [comment]
@eteq I gathered quasi-instantaneously from the module name and the source code comments that `DiscretePRF` is experimental.  I chose to accept the warning because this really is an essential building block for trying out PSF fitting on real data. I only later noticed by accident that `models.py` contained a copy of the same code, which confused me very much.

I will adapt this PR to remove the copy from models.

**Comment by eteq** [comment]
@barentsen Great!  I think this is good assuming the tests pass.

For a bit more backstory: that machinery and the related notebook were written for the last version of psf, which was basically written specifically for Spitzer images (as a sort of quick "stretch goal" for a GSoC student).  The more recent PSF work is more general, but it has probably caused some of what's in there to break.  We are doing a final push now to get the baseline work by @mirca in, and after that it would be great to try to get the stuff in discretePRF up and running (probably for the next version).  So if you need the machinery with the subpixel response information, we'd *love* to have you shepherding it into the new machinery.  Hopefully it will work with minimal modification, but it might needs some fiddly-bits changed like renaming attributes, etc, before it can be moved out of the sandbox.

**Comment by barentsen** [comment]
@eteq Actually it works out of the box: my little experiment is here: barentsen/c48ecf327b9aa132a469b6bdb88bb776

The results are poor, but that's likely because I'm not doing it carefully. Anyway I started playing around for the main purpose of giving feedback to photutils, which I will after the refactoring.

**Pull request merged**
