### PR TITLE
add friendly messages about missing Cython or extension_helpers python packages

### PR DESCRIPTION
**Pull request by dstndstn**
just try to import them in setup.py immediately before use, and print a helpful error message.

### CODE REVIEW

**Comment by larrybradley** [comment]
@dstndstn Why is this needed?  We use PEP518 (`pyproject.toml`) to define build-time dependencies.  `pip install` should pick up any needed build-time dependencies.

**Comment by larrybradley** [comment]
Also see https://github.com/astropy/astropy-APEs/blob/master/APE17.rst

**Comment by dstndstn** [comment]
I ran into this because I checked out the git repo and did a "python3
setup.py install"; what happened first was
https://github.com/astropy/photutils/issues/468
(which is quite a bad failure mode -- for me it didn't print anything
suggesting that cython was expected but missing)
and then the missing extension_helpers.

**Comment by larrybradley** [comment]
`python setup.py install` is generally no longer recommended to install python packages.  To install from source, use `pip install .[all]`.  I will update the install docs for dev installs.

**Comment by dstndstn** [comment]
news to me!

**Comment by pllim** [comment]
This isn't a new problem. See astropy/astropy#9965 for discussion. It is better to use new command than to overcomplicate `setup.py`.

**Comment by bsipocz** [comment]
> news to me!

There has been some significant improvements for python packaging and pip in the recent years, this is one of the nice outcomes, no more confusions about setup.py and whether to use build/install/develop, pip install is now always the answer.

**Pull request closed without merging**
