### PR TITLE
Reduce max line length in pep8speak

### PR DESCRIPTION
**Pull request by pllim**
In a way that will not make @eteq unhappy. :wink: 

(I would go with the default 79 if I can have my way though!)

### CODE REVIEW

**Comment by larrybradley** [comment]
I actually prefer 79 characters also, except for a few rare cases where it's unavoidable.

@bsipocz Do you have a preference?

**Comment by bsipocz** [comment]
yeah, I'm happy with the 79/80, too, otherwise my emacs lights up as a christmas tree, that is quite annoying.

**Comment by pllim** [comment]
Done! :smile:  (Sorry, Erik!)

p.s. I cancelled Travis CI as it is not necessary. Forgot to add `[ci skip]`, my bad!

**Comment by bsipocz** [comment]
Approved, so I'm merging. Thanks @pllim!

**Pull request merged**
