### PR TITLE
Update astropy-helpers to v1.0 and update travis to use astropy v1.0 (and remove workarounds)

### PR DESCRIPTION
**Pull request by bsipocz**
Several updates to ``.travis.yml``:

- use released astropy v1.0 instead of v.1.0rc
- adding ``-w`` option to python3 sphinx build as https://github.com/astropy/astropy-helpers/pull/123 is released in astropy-helpers v0.4.5
- it seems that #202 is fixed on the conda side, remove workaround

### CODE REVIEW

**Comment by bsipocz** [comment]
Also update``astropy-helpers`` to v1.0 and ``ah_bootstrap.py``.

**Comment by bsipocz** [comment]
@astrofrog, @larrybradley - The ``astropy-helpers`` update somehow broke two doctests. Do you think they are genuine? I can't see the reason why they fail with the update, but they don't seem to be simple sporadic fails.

**Comment by astrofrog** [comment]
@bsipocz - maybe the failure is actually due to the new version of scipy released last month?

**Comment by astrofrog** [comment]
We can test that hypothesis by fixing the scipy version, e.g. using ``conda install ... scipy=0.15.0`` or ``conda install ... scipy=0.14``.

**Comment by larrybradley** [comment]
I can't get the tests to fail.  The tests pass fine for me with `scipy 0.15.1`:

```
Numpy: 1.9.1
Scipy: 0.15.1
Matplotlib: 1.4.3
scikit-image: 0.10.1
astropy: 1.1.dev12025
```
They also pass with `astropy 1.0`.

I take a look at this again on Monday.

**Comment by bsipocz** [comment]
They fail locally, too even before the helpers update. However on another server the doctest doesn't even start for the ``rst`` files before updating the helpers, and when directly testing them with ``-t``, I got the error message:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "photutils/_astropy_init.py", line 113, in test
    coverage=coverage, open_files=open_files, **kwargs)
  File "/data/apm36_a/wts/pipeline64/bsipocz/lib/python2.7/site-packages/astropy-1.1.dev12025-py2.7-linux-x86_64.egg/astropy/tests/helper.py", line 153, in run_tests
    "Can not test .rst files without a docs_path "
ValueError: Can not test .rst files without a docs_path specified.
```

**Comment by bsipocz** [comment]
OK, I think I manage to find the reason. Due to some changes in ``astropy/tests/helpers.py`` or related, the tests doesn't run for the rst files for a while in photutils. (E.g. check this recent travislog: https://travis-ci.org/astropy/photutils/jobs/50443621).  
I think this qualifies as a bug in either ``astropy`` or ``astropy-helpers``, there should have been some backward compatibility kept, or at least a big exception raised rather than silently skipping the ``rst`` files.

**Comment by bsipocz** [comment]
The rst testing was off since 472921e24d18e1d440f1960b2a874f72ba503cd0, the upgrade to astropy-helpers to v0.4.4. It's consistent bug, that version of the helpers doesn't test the rst files in other affiliated packages either (checked with astroquery).

Pushed the fix for the doctests:
- the failing part in detection.rst was added after the upgrade, thus never run on travis
- the morphology code was changed since then, thus the rst doctest never run with the new code since the upgrade

**Comment by larrybradley** [comment]
Is this ready to merge?

**Comment by bsipocz** [comment]
@larrybradley - Yes, if you're OK with the changes it's ready to be merged.

**Comment by larrybradley** [comment]
Looks great to me, thanks!

**Pull request merged**
