### PR TITLE
Using new pytest-astropy-header plugin directly

### PR DESCRIPTION
**Pull request by bsipocz**
This should fix the failing astropy-dev build.

### CODE REVIEW

**Comment by larrybradley** [comment]
Does `pytest_astropy_header` need to be installed via PIP_DEPENDENCIES in .travis.yml?  The test failurs are because this package is not found.

**Comment by bsipocz** [comment]
yes, it should come from `pytest-astropy`. ci-helpers installing it in a few cases automatically, maybe it should just always install it whenever it installs astropy.

@astrofrog, any opinions on this?

**Comment by larrybradley** [comment]
`pytest_astropy_header` is not currently installed with `pytest-astropy` using conda, only pip.

**Comment by bsipocz** [comment]
@larrybradley - this seems to be working now, passing on astropy-dev, too.

**Pull request merged**
