### PR TITLE
Add citation file

### PR DESCRIPTION
**Pull request by larrybradley**

### CODE REVIEW

**Comment by bsipocz** [comment]
I think it would be also useful to add a `__bibtex__` and/or `__citation__` to bring up the bibtex info.

**Comment by larrybradley** [comment]
Yes, sounds good!

**Comment by bsipocz** [comment]
I'll open a PR in the evening for it then.

**Comment by larrybradley** [comment]
Since we are recommending the Zenodo reference, which depends on version and doesn't get made until after the release, then won't `__bibtex__` and `__citation__` always be one version behind?

**Comment by bsipocz** [comment]
Yes, I suppose it will always lagging behind except that we can set the DOI to be the canonical one that always resolves to the latest version. The names and order of names might be a slightly bit different though.

**Pull request merged**
