### PR TITLE
TST: pep8speak to use flake8

### PR DESCRIPTION
**Pull request by pllim**
Like this, @bsipocz ?

### CODE REVIEW

**Comment by bsipocz** [comment]
Yes, but then I'm not sure whether the codes are the same between flake8 and pycodestyle, that's the thing that needs to be double checked.

**Comment by bsipocz** [comment]
docs is here for the bot/app: https://github.com/OrkoHunter/pep8speaks, but then everything should be the standard flake8 we might have in setup.cfg

**Comment by pllim** [comment]
From http://flake8.pycqa.org/en/latest/user/error-codes.html , it seems like `flake8` is completely compatible with `pycodestyle` in terms of error codes. It mentions something extra for `pyflakes` and `mccabe` but I don't think those are applicable here?

**Comment by bsipocz** [comment]
OK. Let's merge this then, and see whether the bot starts talking or we need more activation.

**Comment by pllim** [comment]
:crossed_fingers:  :grimacing:

**Pull request merged**
