### PR TITLE
Adding one liner to the docstring of __call__ to fix the rtd latex build

### PR DESCRIPTION
**Pull request by bsipocz**
This should fix the currently broken RTD build.

### CODE REVIEW

**Comment by eteq** [comment]
@bsipocz - this reminds me: actually, in general we do *not* document the `__call__` methods - that should go in the actual class docstring as ``Parameters`` sections.  Will make a tweak to do this in #409

**Comment by eteq** [comment]
Actually on second thought that might not make sense here (I think that convention is sort of outdated anyway).  Anyway, in #410 I'll resolve the differences

**Comment by bsipocz** [comment]
@eteq - We need to have it there, as otherwise the RTD latex builds are failing. @larrybradley spent the time on figuring this out in #405, but I think both of us are open to any other suggestion that makes the latex build happy as still not has a docstring in ``__call__``.

**Comment by bsipocz** [comment]
Ahh, ok, rereading your comment it makes sense. I shouldn't look at issues while hacking at hackweek ;)

**Pull request merged**
