### PR TITLE
MAINT: fix tox v4 compatibility

### PR DESCRIPTION
**Pull request by bsipocz**
While I was at it for astroquery it was an easy fix for photutils, too.

### CODE REVIEW

**Comment by larrybradley** [comment]
@bsipocz Somehow this is breaking the CircleCI tests (table output).  At first glance I was sure the failures were unrelated, but I just reran the CircleCI tests for this PR and main.  main passes, but this PR fails.  Any idea why?

**Comment by bsipocz** [comment]
Hmm, I don't yet see what's the issue with that job, but it's a weird combo, using the oldest supported numpy with astropy dev?

**Comment by bsipocz** [comment]
ssh-ing in to the runner, all tests pass, so this will be an env config issue I suppose:

I run `/opt/python/cp38-cp38/bin/python -m tox -e circleci_32bit` in `/root/project`
```

===================================== 1010 passed, 478 skipped in 92.49s (0:01:32) =====================================
.pkg: _exit> python /opt/python/cp38-cp38/lib/python3.8/site-packages/pyproject_api/_backend.py True setuptools.build_meta
  circleci_32bit: OK (108.68=setup[14.99]+cmd[0.37,93.32] seconds)
  congratulations :) (109.16 seconds)
[root@451d946bb38f project]# 
```

**Review by larrybradley — APPROVED** [review]
Thanks, @bsipocz! 

With help from @taldcroft, I was able to figure out that the table doctest failures were due to a narrow virtual terminal width causing truncated table output.  I suspect that CircleCI may not be parsing the new tox `passenv` list (with commas) correctly and some needed env variable is not being set.  I was able to work around the issue by explicitly setting the CircleCI terminal size.

**Comment by bsipocz** [comment]
Thanks for figuring it out. This case, it's both a doctestplus bug, as well as a bug with the tox config. 
Would you mind opening issues for them? Otherwise I'll try to get there later.

**Comment by larrybradley** [comment]
I think the bug lies with `CircleCI` (everything works fine with Actions).  Why do you think its a `doctestplus` and `tox` bug?

**Comment by bsipocz** [comment]
tox not passing along the env variables, and doctestplus should really work better with ellipses. 

I've run into this issue of it was sensitive of how many columns are in as expected, and it fails when it's more (even when ellipses are present). So, while I'm not sure how to address this issue, ideally it should be more flexible and do partial matching better.

**Pull request merged**
